export enum IconsEnumSvg {
    administration = "./icons/administration.svg",
    arrow_down = "./icons/arrow-down.svg",
    bell = "./icons/bell.svg",
    cog = "./icons/cog.svg",
    comments = "./icons/comments.svg",
    ecosystem = "./icons/ecosystem.svg",
    entities = "./icons/entities.svg",
    entities2 = "./icons/entities2.svg",
    house = "./icons/house.svg",
    house2 = "./icons/house2.svg",
    logout = "./icons/logout.svg",
    network = "./icons/network.svg",
    people = "./icons/people.svg",
    plus = "./icons/plus.svg",
    privacy = "./icons/privacy.svg",
    publications = "./icons/publications.svg",
    search = "./icons/search.svg",
    settings = "./icons/settings.svg",
    user_plus = "./icons/user-plus.svg",
}

export enum IconsEnumPng {
    administration = "./icons/administration.png",
    arrow_down = "./icons/arrow-down.png",
    bell = "./icons/bell.png",
    cog = "./icons/cog.png",
    comments = "./icons/comments.png",
    ecosystem = "./icons/ecosystem.png",
    entities = "./icons/entities.png",
    entities2 = "./icons/entities2.png",
    house = "./icons/house.png",
    house2 = "./icons/house2.png",
    logout = "./icons/logout.png",
    network = "./icons/network.png",
    people = "./icons/people.png",
    plus = "./icons/plus.png",
    privacy = "./icons/privacy.png",
    publications = "./icons/publications.png",
    search = "./icons/search.png",
    settings = "./icons/settings.png",
    user_plus = "./icons/user-plus.png",
}
