export enum IconType {
    administration = "./icons/administration.svg",
    publications = "./icons/publications.svg",
    arrow_down = "./icons/arrow-down.svg",
    ecosystem = "./icons/ecosystem.svg",
    entities2 = "./icons/entities2.svg",
    user_plus = "./icons/user-plus.svg",
    comments = "./icons/comments.svg",
    entities = "./icons/entities.svg",
    settings = "./icons/settings.svg",
    network = "./icons/network.svg",
    privacy = "./icons/privacy.svg",
    people = "./icons/people.svg",
    house2 = "./icons/house2.svg",
    logout = "./icons/logout.svg",
    search = "./icons/search.svg",
    house = "./icons/house.svg",
    plus = "./icons/plus.svg",
    bell = "./icons/bell.svg",
    logo = "./icons/Logo.svg",
    cog = "./icons/cog.svg"
};